# Macos
confirm-close-surface = false
macos-non-native-fullscreen = true
macos-option-as-alt = true
macos-titlebar-style = hidden
macos-window-buttons = hidden
mouse-hide-while-typing = true

# LF
keybind = ctrl+alt+f=text:\x02O

# Lazygit
keybind = ctrl+alt+g=text:\x02G

